### ISSUE TITLE
中文乱码问题

### ISSUE THREAD

**Issue by longyongzhong** [devsapp/start-zip-oss#1]
包含中文字符的文件夹或者文件压缩后，解压出来名字是乱码怎么解决？

**Comment by rsonghuster** [comment]
![image](https://user-images.githubusercontent.com/10919599/172788703-440e8d79-6ba6-4104-8b09-04fb0e993b8b.png)

看起来没有问题

**Comment by longyongzhong** [comment]
> ![image](https://user-images.githubusercontent.com/10919599/172788703-440e8d79-6ba6-4104-8b09-04fb0e993b8b.png)
> 
> 看起来没有问题

是的，我发现在Linux上面没问题，但是在window10上面使用好几个解压工具都是乱码。

**Comment by 15393702382** [comment]
> 包含中文字符的文件夹或者文件压缩后，解压出来名字是乱码怎么解决？

### 看图说话
![1662643065294](https://user-images.githubusercontent.com/18473800/189132641-7e6492fc-ad01-449f-a815-ba253f8e9dca.jpg)
        # 解决文件名中文乱码问题
        try:
            key = key.encode("cp437").decode('gbk')
        except:
            key = key.encode("utf-8").decode('utf-8')

**Comment by longyongzhong** [comment]
> > 包含中文字符的文件夹或者文件压缩后，解压出来名字是乱码怎么解决？
> 
> ### 看图说话
> ![1662643065294](https://user-images.githubusercontent.com/18473800/189132641-7e6492fc-ad01-449f-a815-ba253f8e9dca.jpg) # 解决文件名中文乱码问题 try: key = key.encode("cp437").decode('gbk') except: key = key.encode("utf-8").decode('utf-8')

谢谢！是用这个方法解决了。
